#+title: Flutter Color Viewer (in ClojureDart)
#+OPTIONS: \n:t

The main repository is on [[https://codeberg.org/Kyuvi/Cljd-Flutter-Color-Viewer][Codeberg.org]], if you are viewing this anywhere else, it is just a mirror, please use the [[https://codeberg.org/Kyuvi/Cljd-Flutter-Color-Viewer][Codeberg.org]] repository for pull requests and issues, Thank you.

* Description
A simple application to view the color constants of flutter (except transparent) and their corresponding numerical values.

* Overview
Click on a colored box/container to show the provided accents and shades of that partaicular color, or the alpha/opacity variants in the case of white or black, Clicking on one of those shows a full breakdown of all the values (red, green, blue, alpha and opacity) of that color.

This app can be found online [[https://kyuvi.codeberg.page/Cljd-Flutter-Color-Viewer/@main/web-build/][here]].

* Setup
** Dependencies
- Dart (>= 3.1),
- Flutter (> 3.13),
- [[https://clojure.org][Clojure]] (>= 1.11),
- [[https://github.com/Tensegritics/ClojureDart][ClojureDart]].

** Bulid instructions
From the root folder (containing this README), initialize and compile the ClojureDart code to dart from the command line.

#+BEGIN_SRC sh
clj -M:cljd init

clj -M:cljd compile
#+END_SRC

Then build with flutter for appropriate platform (see =flutter build --help=)
i.e. to build for linux,

#+BEGIN_SRC shell
flutter build linux
#+END_SRC

* Motivation
Written to experiment with [[https://github.com/Tensegritics/ClojureDart][ClojueDart]] and also so I have a way to view the color constants of flutter easily.

* Donations

If you would like to support my work, please donate.

** Monero
42s4DCgjk2sguR8x1H4Svx7sBuysvrRHGCK3pfQTcEerNBUGhT43gMy6noctiGeVeo61aFzsQfGwVTxNmruy3dqb8PAyYZM

** Bitcoin
bc1quymsg5tvyvqkcn35zzujfdrdwgxnakqaptqc5k

** LiteCoin
ltc1q8ese8e8rl9c80emqgvek24gylz32u3d76v2e9q
